services:
  app:
    platform: linux/x86_64
    ports:
      - "8800:80"
      - "5173:5173"
    build: ./docker/app
    container_name: image_serves
    volumes:
      - ./image_serves/:/var/www/html
    # env_file:
    #   - ./image_serves/.env.example
    networks:
      - default_network
    depends_on:
      - db
      - mailhog

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: image_serves_db
    hostname: image_serves_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: image_serves_db
      MYSQL_USER: image_serves_user
      MYSQL_PASSWORD: image_serves_pass
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3333:3306
    # env_file:
    #   - ./image_serves/.env.example
    networks:
      - default_network

  mailhog:
    image: mailhog/mailhog
    container_name: image_serves_mailhog
    hostname: image_serves_mailhog
    ports:
      - "8025:8025"
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
